import { Refs, useShellLang } from '@fasl-work/caos-app-shell';

export default function Implementation() {
  const es = useShellLang() === 'es';
  return (
    <div className="page-body prose">
      <div className="page-head">
        <h1>{es ? 'Implementación' : 'Implementation'}</h1>
        <p className="lede">{es ? 'El motor de eventos discretos determinista, el pipeline de aprendizaje offline (loguear→entrenar→ONNX) y la frontera honesta con el runtime liviano en el navegador.' : 'The deterministic discrete-event engine, the offline learning pipeline (log→train→ONNX) and the honest boundary with the thin in-browser runtime.'}</p>
      </div>
      <section>
        <h2>{es ? 'El motor de eventos discretos' : 'The discrete-event engine'}</h2>
        <p>{es ? 'El núcleo es una simulación de eventos discretos con avance al próximo evento: una lista de eventos futuros (cola binaria) con clave de orden total (tiempo entero en centisegundos, prioridad, secuencia) — el contador de secuencia monótono es la piedra angular del determinismo. El PRNG es xoshiro128** sobre enteros, con flujos nombrados; las duraciones se redondean a ticks al agendar. La misma corrida es bit-reproducible por motor; la traza commiteada es la verdad entre entornos.' : 'The core is a next-event-time-advance discrete-event simulation: a future-event list (binary heap) with a total-order key (integer centisecond time, priority, sequence) — the monotonic sequence counter is the determinism keystone. The PRNG is xoshiro128** over integers, with named streams; durations are rounded to ticks at schedule time. The same run is bit-reproducible per engine; the committed trace is the cross-environment truth.'}</p>
        <Refs ids={['banks2010', 'law2015', 'lecuyer2002', 'ieee754']} label="Refs" />

        <h2>{es ? 'El pipeline de aprendizaje offline' : 'The offline learning pipeline'}</h2>
        <PipelineSVG es={es} />
        <p>{es ? 'En vez de re-portar el simulador a Python (riesgo de divergencia), se GENERA el dataset corriendo el DES real y logueando, en cada decisión de despacho, la matriz de features por pala (cola, en-tránsito, ocupación, cuándo se libera, backlog, viaje) + la acción tomada + las toneladas del episodio — 67.645 decisiones reales. Un script en Python (ambiente aislado) entrena dos redes de puntuación por pala:' : 'Rather than re-port the simulator to Python (divergence risk), the dataset is GENERATED by running the real DES and logging, at each dispatch decision, the per-shovel feature matrix (queue, in-transit, loading, when-it-frees, backlog, travel) + the action taken + the episode tonnes — 67,645 real decisions. A Python script (isolated environment) trains two per-shovel scoring nets:'}</p>
        <ul>
          <li>{es ? <><b>Política (imitación ponderada por recompensa, RWR):</b> reproduce las decisiones de referencia ponderadas por las toneladas del episodio → aprende los patrones de los buenos episodios.</> : <><b>Policy (reward-weighted imitation, RWR):</b> reproduces the reference decisions weighted by episode tonnes → learns the good-episode patterns.</>}</li>
          <li>{es ? <><b>BC-best:</b> clona la mejor heurística por toneladas medianas.</> : <><b>BC-best:</b> behaviour-clones the best heuristic by median tonnes.</>}</li>
        </ul>
        <p>{es ? 'Ambas se exportan a ONNX. El encoding de features es la ÚNICA fuente de verdad: el navegador reconstruye los mismos features antes de inferir.' : 'Both export to ONNX. The feature encoding is the single source of truth: the browser rebuilds the same features before inference.'}</p>
        <Refs ids={['peters2007', 'mnih2015', 'hasselt2016', 'noriega2024']} label="Refs" />

        <h2>{es ? 'La frontera precálculo / en vivo' : 'The precompute / live boundary'}</h2>
        <p>{es ? 'Frontera honesta: el entrenamiento de las redes es PRECÁLCULO offline (Python). En VIVO, el motor DES corre en el navegador (el cálculo es liviano: una corrida de turno es milisegundos), las políticas clásicas y las aprendidas (forward sincrónico de las redes) deciden en cada despacho, y el inspector de decisión ejecuta el ONNX vía onnxruntime-web (WASM de un solo hilo — GitHub Pages no permite COOP/COEP) para mostrar los puntajes por pala en vivo. Modelos ~6 KB cada uno; sin re-alojar datos crudos.' : 'An honest boundary: training the nets is offline PRECOMPUTE (Python). LIVE, the DES runs in the browser (the compute is light: a full-shift run is milliseconds), the classical and learned policies (a synchronous forward of the nets) decide each dispatch, and the decision inspector runs the ONNX via onnxruntime-web (single-threaded WASM — GitHub Pages cannot set COOP/COEP) to show the per-shovel scores live. Models ~6 KB each; no re-hosted raw data.'}</p>
        <Refs ids={['white1986', 'kuhn1955']} label="Refs" />
      </section>
    </div>
  );
}

function PipelineSVG({ es }: { es: boolean }) {
  const stage = (x: number, t: string, sub: string, fill: string) => (
    <g><rect x={x} y={30} width="120" height="50" rx="7" fill={fill} stroke="var(--color-border)" /><text x={x + 60} y={51} textAnchor="middle" fill="var(--color-fg)" fontSize="12" fontWeight="600">{t}</text><text x={x + 60} y={67} textAnchor="middle" fill="var(--color-fg-subtle)" fontSize="10">{sub}</text></g>
  );
  const arr = (x: number) => <line x1={x} y1={55} x2={x + 18} y2={55} stroke="var(--color-fg-subtle)" strokeWidth="1.4" markerEnd="url(#pp-a)" />;
  const xs = [10, 158, 306, 454];
  const S: [string, string, string][] = [
    [es ? 'DES real' : 'real DES', es ? 'loguear decisiones' : 'log decisions', 'var(--color-surface)'],
    ['dataset', '67k', 'var(--color-surface)'],
    [es ? 'Entrenar' : 'Train', 'RWR + BC', 'color-mix(in oklab, #f85149 16%, var(--color-surface))'],
    ['ONNX', es ? '→ navegador' : '→ browser', 'color-mix(in oklab, var(--color-accent) 14%, var(--color-surface))'],
  ];
  return (
    <svg viewBox="0 0 590 110" width="100%" style={{ maxWidth: 590, display: 'block', margin: '0.5rem auto', font: '12px var(--font-sans, sans-serif)' }} role="img" aria-label={es ? 'Pipeline' : 'Pipeline'}>
      <defs><marker id="pp-a" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="var(--color-fg-subtle)" /></marker></defs>
      {S.map((s, i) => <g key={i}>{stage(xs[i], s[0], s[1], s[2])}{i < 3 && arr(xs[i] + 120)}</g>)}
      <text x={295} y={100} textAnchor="middle" fill="var(--color-fg-subtle)" fontSize="10.5">{es ? '↑ offline (Python, ambiente aislado)        DES + inferencia en vivo en el navegador ↓' : '↑ offline (Python, isolated env)        DES + live inference in the browser ↓'}</text>
    </svg>
  );
}
